const paragraphs = [
"Everything you can imagine is real. I would love to be skinnier, I really would, but the ponds here are so shallow and the creeks are so narrow; the sidewalks are clogged and the shoes on my feet feel heavy because of the care I see in everyone’s eyes Currently, I am behind a boy in a letterman jacket and faded blue jeans. We are shambling along in the midst of thousands, inching our way past the plazas of coffee shops and convenience stores and soaring apartment buildings, and I think we’re going to be late for our eight o’clock lecture",
"Normality is a paved road: it’s comfortable to walk but no flowers grow ;When Ralph asked me for my help, I thought we were going to be selling drugs. That’s the way he made it seem: he came to me after our lecture one Monday morning and told me he was trying to make some quick cash.",
"Live as if you were to die tomorrow; After Pradyumna had finished his studies, he took all his possessions and sold them. Unfortunately, the money he earned didn’t even come close to a flight ticket. All he could afford was a cheap and used bicycle. Many would have been greatly disappointed, some would have even given up. But not Pradyumna. Instead of allowing the difficult circumstances to stop him from seeing his beloved wife again, he met the decision to use what he had in order to see her again. Nothing could stop him from reuniting with his wife, even if that meant an exhausting bicycle ride half around the world",
"It always seems impossible until it's done;There are people who say love can move mountains. This might not be physically possible, but Dashrath Manjhi, also known as the ‘Mountain Man’, came quite close. In one day of his life, his wife fell while crossing a nearby hill and hurt herself seriously. She needed quick medical assistance, but that wasn’t possible due to the hill that isolated their small village from the next town. Tragically enough, his wife died from the serious injuries before Dashrath could do anything about it. It was the night when Dashrath Manjhi decided to carve a small path through the mountain in order to give his village easier access to medical assistance.",
"The time is always right to do what is right;Alex and his grandmother always had a unique bond with each other. He would spend hours with her, listening to his grandmother’s stories of a lifetime. She once told him that she had met his grandfather a long time after graduating from high school. This was also the reason why she was never asked out to go to prom. When the day of Alex’s prom had arrived, his grandmother was so excited for him. She had watched him save money for months so that he could afford a tuxedo and even a limousine",
"Happiness depends upon ourselves; In my junior year of high school, this guy asked me on a date. He rented a Redbox movie and made a pizza. We were watching the movie and the oven beeped so the pizza was done. He looked me dead in the eye and said, “This is the worst part.” I then watched this boy open the oven and pull the pizza out with his bare hands, rack and all, screaming at the top of his lungs. We never had a second date.",
"If you don’t like the road you’re walking, start paving another one;I failed the first quarter of a class in middle school, so I made a fake report card. I did this every quarter that year. I forgot that they mail home the end-of-year cards, and my mom got it before I could intercept with my fake. She was PISSED—at the school for their error. The teacher also retired that year and had already thrown out his records, so they had to take my mother’s “proof” (the fake ones I made throughout the year) and “correct” the “mistake.” I’ve never told her the truth.",
"Live a simple life; you will own the most beautiful treasures of the world! I went to this girl’s party the week after she beat the shit out of my friend. While everyone was getting trashed, I went around putting tuna inside all the curtain rods and so like weeks went by and they couldn’t figure out why the house smelled like festering death. They caught me through this video where these guys at the party were singing Beyoncé while I was in the background with a can of tuna.",
"A simple life gives birth to more clarity, inner peace and meaningful relationships;One time my drama class’s teacher had gone home sick so we were just put in a classroom with a movie to entertain us for the period when an alarm went off. None of us were sure if it was the fire alarm or the lockdown alarm, so we all head out into the hall to check and no one’s out there, so we head back in and climb under our desks as is lockdown procedure. Cut to an hour or so later when a teacher bursts in and nearly dies of relief because the school was on fire and we were the only students not accounted for and half the faculty and fire department had been searching for us for ages. Literally, the whole school had filled with smoke while we’d kept super safe under our wooden desks.",
"Because you are alive, everything is possible; During my sophomore year of high school, we were doing silent work and my history teacher said that we could listen to music but if it was too loud he would “break our headphones.” so I’m doing my work quietly with my music on low, and this obnoxious kid sitting next to me had his music really loud. I could hear it over my music but ignored it. My teacher thought it was me. So he comes up to me & ripped my BRAND NEW Apple headphones, looking ruthless. He suddenly realized it was the guy next to me and he was completely embarrassed. He came in the next day with a new pair and an apology note taped to them. He couldn’t look me in the eye for the rest of the year.",
"Life isn't about finding yourself. Life is about creating yourself;: I have a friend who I’ve known since I was very little. One day, when he was six, I was at his house when he got this absolutely god-awful stomach pain. I mean, he was literally writhing in pain. So, his mom took him to the doctor’s office, where the doctor took one look and told her to take him to the ER. She feared something along the lines of an intestinal rupture. About half way to the hospital, my friend suddenly let rip the loudest, most powerful fart any of us had ever heard. I swear to God he levitated. We thought the upholstery in the car seat had ripped. After a good 30 seconds of intense farting, he looked at his mom and said, “I feel all better now!",
"Our truest life is when we are in dreams awake;So in 8th grade I used to read during class a lot. At the time I was reading an Artemis Fowl book, and for some reason I had two copies of the same book. So one day in my English class we were reading this other book (which I had already finished reading three days earlier), I was reading my own book and when it was finally my turn to read, I had no idea where we were. So the teacher took my book away, I found my spot, read the part and passed it to the next person to start reading.",
"The great thing in this world is not so much where we are, but in what direction we are going;Now my friend that sat two chairs down from me was also reading Artemis at the same time as me and with a quick look to him he knew exactly what I was planning. He took it out and passed it over without hesitation. I opened to a random spot and just pretended like I was reading. (At this point it was just to mess with my teacher",
"A warm smile is the universal language of kindness;One time in 6th grade we were at recess and while I was running to my friends, I just so happened to kick a HUGE rock (keep in mind, I was wearing flip-flops so it hurt like hell) and without thinking, I shouted at the top of my lungs “***!” And with my god-awful luck, my math teacher was sitting at the bench right BESIDE ME. He then took me inside to what I thought was yell at me but he just couldn’t stop laughing and sent me back outside with a literal candy bar. He is still my favorite teacher I’ve ever had",
"Simplicity is the ultimate sophistication;Since my crush sits behind me in class, when we stood up to do the pledge I stood up too fast and I stumbled over to him so to not fall on the ground I reached to grab his desk but I accidentally GRABBED HIM and I ended up falling on top of him and we both screamed. Luckily I didn’t hurt or crush him. My teacher and everyone else started laughing and I got so red afterwards. Now when we stand up for the pledge, he moves all the way to the back of the room away from me",
"Love yourself first and everything else falls into line; OK, so one time when I was really little I had a best friend who was kinda strange but so my mom got a call one day asking if she was over at my house because they couldn’t find her and so they call again about two hours later to ask if we could help look for her and so about three hours of looking we had basically covered the entire neighborhood and they were about to call the police and we decided to check their house one more time and my mom went into her room and found her completely naked and sleeping on the top of a super tall shelf in her closet",
"Lead from the heart, not the head;So I was sitting at a lecture when I feel like being stared at, and in the corner of my eye I see this really handsome guy, who’s literally just staring at me. I don’t think much of it and continue to listen to the professor. After the lecture the guy comes up to me, and lays his hand on head and I’m like “eeeehm, what are you doing” and he stares me dead in the eyes and says “I’ve never seen such a gorgeous skull” and then he turns around and leaves.",
"Live in the sunshine, swim the sea, drink the wild air; : Once upon a time I had a friend that was going to a Panic! At The Disco concert and she promised me she would face time me so that I could watch with her. So she messaged me at like the middle of the night telling me to answer her FaceTime call but I was at my neighbors house (which also happened to be my cousins house) so I started running out the door and my sister followed me behind and was chasing after me. She asked me where I was going so I started running as fast as I could screaming WE HAVE TO GET HOME, IM NOT GONNA MAKE IT! I NEED TO SEE, WHY CANT I SEE!?!” ",
"Life is like riding a bicycle. To keep your balance, you must keep moving;So about a year ago, I was in Phys. Ed class, and we went around the neighborhood for a jog at the beginning of each class. I hadn’t done it before because of medical reasons, but the teacher evidently forgot about it. I’m incredibly bad with directions and easily distracted, so I lost sight of the rest of the group and went completely the wrong way. I ended up being lost for TWO AND A HALF HOURS. the best part is that I single handedly changed my school’s Phys. Ed policy",
"It is never too late to be what you might have been; One time way back in sixth grade math class I had to fart really bad. Me being the idiot that I am decided that it would be silent. Big surprise it wasn’t. The only person talking was the teacher and she was interrupted by freaking cannon fire farts. She said she was disappointed I couldn’t hold it in and proceeded to tell a story of how she taught a famous athlete who did nearly the same thing"

]; 